### ISSUE TITLE
Please publish latest version (0.2.0) to NPM

### ISSUE THREAD

**Issue by galenandrew** [muzzley/good-bunyan#11]
383d11471f44d1a05275671ca709c034abf94c08 bumps version to v0.2.0, but NPM still has v0.1.2 as the latest.

Please run `npm publish` to publish the latest release to NPM.

Also, run `git push --tags` to push your release tags to GitHub.

**Comment by jadams74** [comment]
:+1:

**Comment by tiagoalves** [comment]
It has been published just now.
