### ISSUE TITLE
Is this reporter working with Good >= 7

### ISSUE THREAD

**Issue by yonjah** [muzzley/good-bunyan#12]
I recently came a cross an issue with `good-winston` being wrongly implemented as a transform stream instead of a writable stream (https://github.com/lancespeelmon/good-winston/issues/6).

It seems like `good-bunyan` is doing the same which might cause it to stop logging after ~31 events.

You can check the discussion on good -
https://github.com/hapijs/good/issues/518

**Comment by aalimovs** [comment]
It doesn't seem to stop for me after ~31 events. I did a 10000 without any issues. What node version you've tried this on?

**Comment by yonjah** [comment]
I tested it both with node 4.x and 6.x 
How did you setup the test env ?

**Comment by tiagoalves** [comment]
I also tested it with lots of messages and saw no issue.

Anyway, I still changed the stream type from transform to writable in branch [fix/transform-to-writable-stream](https://github.com/muzzley/good-bunyan/tree/fix/transform-to-writable-stream) and this also works correctly with thousands of messages.

If any of you guys want to test it before I publish the changes, let me know.

**Comment by yonjah** [comment]
I ran the tests and original implementation is actually working.
This is due to the fact that no data id passed to from the Transform callback so the stream never gets saturated.

But using writable stream makes more since and the implementation seems solid.

**Comment by tiagoalves** [comment]
@yonjah, thanks for bringing this issue to our attention and for helping us test it. It's fixed and published to npm in v1.1.0.
