### ISSUE TITLE
Error: Cannot pipe, not readable

### ISSUE THREAD

**Issue by joshferrell** [muzzley/good-bunyan#17]
I get an error when I try to pipe good-bunyan into white-out. Here's my configuration:

```
export const good = {
    register: require('good'),
    options: {
        reporters: {
            bunyan: [{
                module: 'good-bunyan',
                args: [
                    { ops: '*', request: '*', log: '*', response: '*', error: '*'},
                    { logger: log }
                ]
            }, {
                module: 'white-out',
                args: [{
                  password: 'censor'
                }]
            }]
        }
    }
};
```

I'm using good-bunyan in conjunction with white-out a censoring plugin referenced [in the Hapi documentation](https://github.com/hapijs/good/blob/master/examples/censoring-with-white-out.md). Whenever good attempts to pipe the output of good-bunyan into white-out, it seems to fail. However, good-bunyan by itself works fine.

Here's the error message I get from the server:
```
There was a problem (Error: Cannot pipe, not readable) in bunyan and it has been destroyed.
Error: Cannot pipe, not readable
    at GoodBunyan.Writable.pipe (_stream_writable.js:186:22)
    at pipe (/project/node_modules/pump/index.js:54:15)
    at Array.reduce (native)
    at pump (/project/node_modules/pump/index.js:77:18)
    at Pumpify.setPipeline (/project/node_modules/pumpify/index.js:39:5)
    at new Pumpify (/project/node_modules/pumpify/index.js:15:30)
    at Function.Pumpify [as obj] (/project/node_modules/pumpify/index.js:13:44)
    at internals.forOwn (/project/node_modules/good/lib/monitor.js:147:53)
    at Object.internals.forOwn (/project/node_modules/good/lib/monitor.js:230:9)
    at Monitor.start (/project/node_modules/good/lib/monitor.js:105:19)
```

Node version: v7.10.0
bunyan: 1.8.10
good: 7.2.0
good-bunyan: 1.3.0
hapi: 16.4.3,

**Comment by jSherz** [comment]
Have you tried placing the white-out module before good-bunyan? That should filter the data before it's logged.

**Comment by joshferrell** [comment]
Yes, reversing it works. However, this breaks from the standard defined by the [hapijs documentation](https://github.com/hapijs/good/blob/master/examples/censoring-with-white-out.md), where events from good-squeeze are piped into white-out then piped into good-console.

If you have a server with tons of logs, there's no point in having white-out process logs that will be filtered by the good-bunyan reporter anyways.

**Comment by jSherz** [comment]
That's true, however good-bunyan is currently implemented as a [writable stream](https://nodejs.org/api/stream.html#stream_class_stream_writable) (see #12 for discussion) and so only acts as a destination - not something that produces data that can be streamed.

You could use a formatter, as in the example in the README?

```javascript
const options = {
  reporters: {
    bunyan: [{
      module: 'good-bunyan',
      args: [
        { ops: '*', response: '*', log: '*', error: '*', request: '*' },
        {
          logger: logger,
          levels: {
            ops: 'debug'
          },
          formatters: {
            response: (data) => {
              // ...
              // Perform white-out cleaning here
              // ...
              return 'Response for ' + data.path;
            }
          }
        }
      ]
    }]
  }
};
```

**Comment by joshferrell** [comment]
Ah, I see. So the more apt comparison would be good-bunyan is more like good-console than good-squeeze? If that's the case, I feel that the event listener is a bit misleading as good-squeeze should be handling event listening and good-bunyan should just map events to log types.

**Comment by jSherz** [comment]
I believe that good-console is just a formatter and doesn't handle output whereas good-bunyan formats and outputs. This example below works if you want to follow the good-squeeze pattern:

```javascript
'use strict';

const Hapi = require('hapi');
const Good = require('good');
const bunyan = require('bunyan');

const logger = bunyan.createLogger({ name: 'myapp', level: 'trace' });
const server = new Hapi.Server();
server.connection({ port: 3000, host: 'localhost' });

server.route({
    method: 'GET',
    path: '/',
    handler: function (request, reply) {
        reply('Hello, world!');
    }
});

server.route({
    method: 'GET',
    path: '/{name}',
    handler: function (request, reply) {
        reply('Hello, ' + encodeURIComponent(request.params.name) + '!');
    }
});

server.register({
    register: Good,
    options: {
        reporters: {
            console: [{
                module: 'good-squeeze',
                name: 'Squeeze',
                args: [{
                    response: '*',
                    log: '*'
                }]
            },
            {
                module: 'white-out',
                args: [{
                  password: 'censor'
                }]
            },
            {
                module: 'good-bunyan',
                args: [
                  { ops: '*', response: '*', log: '*', error: '*', request: '*' },
                  {
                    logger: logger,
                    levels: {
                      ops: 'debug'
                    }
                  }
                ]
            }]
        }
    }
}, (err) => {

    if (err) {
        throw err; // something bad happened loading the plugin
    }

    server.start((err) => {
        if (err) {
            throw err;
        }

        server.log('info', 'Server running at: ' + server.info.uri);
        server.log('info', {super: true, secret: true, password: 'asdfasdf'})
    });
});
```

Produces:

```
{"name":"myapp","hostname":"localhost","pid":8867,"level":30,"msg":"[log] Server running at: http://localhost:3000","time":"2017-08-04T06:13:25.359Z","v":0}
{"name":"myapp","hostname":"localhost","pid":8867,"level":30,"super":true,"secret":true,"password":"XXXXXXXX","msg":"[log]","time":"2017-08-04T06:13:25.361Z","v":0}
```

**Comment by joshferrell** [comment]
There are a couple issues I have with that though. For starters, good-bunyan may have a different filter than good-squeeze. So in your case, good-bunyan is expecting error, request, ops, but will never get them because good-squeeze has filtered them out.

Also, as you note, you're running two instances of good-squeeze. Good-bunyan seems to fit the formula for [good-winston](https://github.com/lancespeelmon/good-winston). Nevertheless, this isn't really an issue with good-bunyan, and I will close this issue as the developers of this package wrote it to handle events and bunyan logging.
