### ISSUE TITLE
good 7.0.0

### ISSUE THREAD

**Issue by aalimovs** [muzzley/good-bunyan#8]
Hey,

Long time `bunyan` user since `restify`. Hopped on `hapi` bandwagon just recently and trying to implement `good-bunyan`. 

However, am I right to assume it is not currently compatible with the `good`'s recent 7.0.0 release?

**Comment by pklingem** [comment]
I'm having problems as well with good 7.x

**Comment by StefanoMagrassi** [comment]
@aalimovs @pklingem I submitted a PR (#9) in order to resolve `good` 7.x.x compatibility.

Untill it will be merged you can set [my forked repo](https://github.com/StefanoMagrassi/good-bunyan) as dependency in [package.json](https://docs.npmjs.com/files/package.json#github-urls).

**Comment by galenandrew** [comment]
For some reason #10 was not merged into master, thus is not part of the `v0.2.0` release. ¯\_(ツ)_/¯

Can this get merged into master so things work?

**Comment by tiagoalves** [comment]
I'm adding tests to #10 and it should be ready in a few days.

**Comment by gordysc** [comment]
Any updates or an ETA for this?

**Comment by tiagoalves** [comment]
I finally got around finishing merging PR #9 and adding tests and some minor fixes. It has already been published to npm as version 1.0.0.

@StefanoMagrassi, thank you again for the PR!
